# Generated by Django 5.1.5 on 2025-02-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planner',
            old_name='event_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='planner',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='planner',
            name='event_time',
        ),
        migrations.AddField(
            model_name='planner',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planner',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
